<?php

$peliculas = [
  [
    'Nombre de la película' => 'El Padrino',
    'Imagen (URL)' => 'https://imgs.search.brave.com/u33RanResqFds8B2frgt0XZFscr0JasglB94Rs_r5J0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS50bWRiLm9yZy90/L3AvdzMwMC9kZkVR/TXVaTUljUGdDN250/MDdEOXVWUWk3VHYu/anBn',
    'Horarios de proyección' => ['16:00', '19:00', '22:00'],
    'Sinopsis' => 'La historia de la familia Corleone, una de las más poderosas de la mafia italiana en Nueva York.',
    'Duración' => '175 min',
    'Director' => 'Francis Ford Coppola',
    'Reparto' => ['Marlon Brando', 'Al Pacino', 'James Caan'],
    'Calificación (+16)' => true,
    'Género' => ['Drama', 'Crimen'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=gCVj1LeYnsc',
    'Nota' => 5,
  ],
  [
    'Nombre de la película' => 'Titanic',
    'Imagen (URL)' => 'https://imgs.search.brave.com/OWbjP48e7Mz80Kw04Hxfa3HNr7Vrem1OURuYKxl6NYA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lcy53/ZWIuaW1nMy5hY3N0/YS5uZXQvY18zMTBf/NDIwL21lZGlhcy9u/bWVkaWEvMTgvODYv/OTEvNDEvMTk4NzAw/NzMuanBn',
    'Horarios de proyección' => ['15:30', '19:30'],
    'Sinopsis' => 'Un joven artista y una joven de la alta sociedad se enamoran durante el fatídico viaje inaugural del Titanic.',
    'Duración' => '195 min',
    'Director' => 'James Cameron',
    'Reparto' => ['Leonardo DiCaprio', 'Kate Winslet'],
    'Calificación (+16)' => false,
    'Género' => ['Romance', 'Drama'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=2e-eXJ6HgkQ',
    'Nota' => 4,
  ],
  [
    'Nombre de la película' => 'El Señor de los Anillos: La Comunidad del Anillo',
    'Imagen (URL)' => 'https://imgs.search.brave.com/lOX2YyuaB0WwR4FzEU4Xf9AyBZsFi4chuuwoYEaXkxo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9uYXR1/cnZpdGEuZXMvX25l/eHQvaW1hZ2U_dXJs/PWh0dHBzOi8vaW1h/Z2UudG1kYi5vcmcv/dC9wL3c1MDAvLzZv/b201UVlRMnlRVE1K/SWJudmJrQkw5Y0hv/Ni5qcGcmdz03NTAm/cT03NQ',
    'Horarios de proyección' => ['12:00', '18:00', '21:30'],
    'Sinopsis' => 'Un joven hobbit debe destruir un anillo poderoso para evitar la dominación de la Tierra Media.',
    'Duración' => '178 min',
    'Director' => 'Peter Jackson',
    'Reparto' => ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
    'Calificación (+16)' => true,
    'Género' => ['Fantasía', 'Aventura'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=V75dMMIW2B4',
    'Nota' => 5,
  ],
  [
    'Nombre de la película' => 'Avatar',
    'Imagen (URL)' => 'https://imgs.search.brave.com/8f88UtqhPsTvxx-bDIcc05pmDDNvFp7VuubZvZF88xM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lcy53/ZWIuaW1nMi5hY3N0/YS5uZXQvY18zMTBf/NDIwL3BpY3R1cmVz/LzIyLzA4LzMwLzEy/LzQyLzA1MzUwNjIu/anBn',
    'Horarios de proyección' => ['13:00', '17:00', '21:00'],
    'Sinopsis' => 'Un exmarine se une a los nativos Na’vi en Pandora en medio de un conflicto por la explotación de recursos.',
    'Duración' => '162 min',
    'Director' => 'James Cameron',
    'Reparto' => ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver'],
    'Calificación (+16)' => false,
    'Género' => ['Ciencia ficción', 'Aventura'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=5PSNL1qE6VY',
    'Nota' => 4,
  ],
  [
    'Nombre de la película' => 'Gladiator',
    'Imagen (URL)' => 'https://imgs.search.brave.com/a-accjtl00S0bqut6QXpYAPV4bxJQ464985FsVeXWh8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjE4bUMzZGZnZUwu/anBn',
    'Horarios de proyección' => ['16:30', '20:30'],
    'Sinopsis' => 'Un general romano es traicionado y convertido en esclavo, pero lucha en la arena para vengar a su familia.',
    'Duración' => '155 min',
    'Director' => 'Ridley Scott',
    'Reparto' => ['Russell Crowe', 'Joaquin Phoenix'],
    'Calificación (+16)' => true,
    'Género' => ['Acción', 'Drama'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=owK1qxDselE',
    'Nota' => 5,
  ],
  [
    'Nombre de la película' => 'Inception (Origen)',
    'Imagen (URL)' => 'https://imgs.search.brave.com/QWgQHTGm35oAzcFupPRl9_PC0MAHniPrNTgA1P3L9BU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzF5MjlTQVQzekwu/anBn',
    'Horarios de proyección' => ['14:00', '19:00', '22:30'],
    'Sinopsis' => 'Un ladrón especializado en entrar en los sueños debe realizar la misión más compleja de su carrera.',
    'Duración' => '148 min',
    'Director' => 'Christopher Nolan',
    'Reparto' => ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    'Calificación (+16)' => true,
    'Género' => ['Ciencia ficción', 'Acción'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    'Nota' => 5,
  ],
  [
    'Nombre de la película' => 'Joker',
    'Imagen (URL)' => 'https://imgs.search.brave.com/OfTo-azkxh1wN82rFMO4GSLrAk2DK4lx1tMljpbvbVc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzFLUE92dS1oT0wu/anBn',
    'Horarios de proyección' => ['17:00', '21:00'],
    'Sinopsis' => 'Arthur Fleck, un hombre con problemas mentales, se convierte en el icónico villano Joker en Gotham.',
    'Duración' => '122 min',
    'Director' => 'Todd Phillips',
    'Reparto' => ['Joaquin Phoenix', 'Robert De Niro'],
    'Calificación (+16)' => true,
    'Género' => ['Drama', 'Thriller'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
    'Nota' => 4,
  ],
  [
    'Nombre de la película' => 'Pulp Fiction',
    'Imagen (URL)' => 'https://imgs.search.brave.com/nN5u61Tq9mmAD55KPl7YNo8SFY1mWZlZzC0qwHSYpm0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMucG9zdGVycy5j/ei9pbWFnZS8zNTAv/Y2FydGVsZXMtZGUt/bWV0YWwvcHVscC1m/aWN0aW9uLXVtYS1v/bi1iZWQtaTIxMjky/NS5qcGc',
    'Horarios de proyección' => ['18:00', '22:00'],
    'Sinopsis' => 'Historias entrelazadas de criminales en Los Ángeles con diálogos icónicos y humor negro.',
    'Duración' => '154 min',
    'Director' => 'Quentin Tarantino',
    'Reparto' => ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'],
    'Calificación (+16)' => true,
    'Género' => ['Crimen', 'Drama'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    'Nota' => 3,
  ],
  [
    'Nombre de la película' => 'Forrest Gump',
    'Imagen (URL)' => 'https://imgs.search.brave.com/bZDnrOLPY7cSUc_AKC0_LnO__FJrhgxz0ltXEQ-H90w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lcy53/ZWIuaW1nMy5hY3N0/YS5uZXQvY18zMTBf/NDIwL21lZGlhcy9u/bWVkaWEvMTgvOTMv/MjQvMTUvMjAyNDQ3/ODkuanBn',
    'Horarios de proyección' => ['12:30', '19:15'],
    'Sinopsis' => 'La vida de Forrest, un hombre sencillo con un corazón enorme, que presencia y protagoniza momentos históricos.',
    'Duración' => '142 min',
    'Director' => 'Robert Zemeckis',
    'Reparto' => ['Tom Hanks', 'Robin Wright'],
    'Calificación (+16)' => false,
    'Género' => ['Drama', 'Romance'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=bLvqoHBptjg',
    'Nota' => 5,
  ],
  [
    'Nombre de la película' => 'Avengers: Endgame',
    'Imagen (URL)' => 'https://imgs.search.brave.com/visTLxyXUqUT0lH4zkwny5zeLzlJ_fH2Q1sxLkrDFpM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZWNhcnRlbGVyYS5j/b20vY2FydGVsZXMv/ODkwMC84OTAyLzA0/MV9wLmpwZw',
    'Horarios de proyección' => ['13:15', '17:45', '21:45'],
    'Sinopsis' => 'Los Vengadores se unen una vez más para derrotar a Thanos y revertir la catástrofe universal.',
    'Duración' => '181 min',
    'Director' => 'Anthony Russo, Joe Russo',
    'Reparto' => ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
    'Calificación (+16)' => true,
    'Género' => ['Acción', 'Ciencia ficción'],
    'URL del tráiler (YouTube)' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
    'Nota' => 4,
  ],
];

?>

